-- 表结构定义（仅包含CREATE TABLE语句）
-- 这个文件被 database.js 使用来创建表

-- 创建用户表
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE,
  signup_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  trial_start DATE,
  simulation_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 创建投资组合表
CREATE TABLE IF NOT EXISTS portfolios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  cash_balance DECIMAL(15,2) DEFAULT 10000.00,
  total_value DECIMAL(15,2) DEFAULT 10000.00,
  total_cost DECIMAL(15,2) DEFAULT 0.00,
  total_return DECIMAL(15,2) DEFAULT 0.00,
  total_return_percent DECIMAL(5,2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 创建持仓表
CREATE TABLE IF NOT EXISTS positions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  portfolio_id INT NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  shares INT NOT NULL,
  avg_cost DECIMAL(10,2) NOT NULL,
  total_cost DECIMAL(15,2) NOT NULL,
  current_price DECIMAL(10,2) DEFAULT 0.00,
  current_value DECIMAL(15,2) DEFAULT 0.00,
  unrealized_gain DECIMAL(15,2) DEFAULT 0.00,
  unrealized_gain_percent DECIMAL(5,2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE,
  UNIQUE KEY unique_portfolio_symbol (portfolio_id, symbol)
) ENGINE=InnoDB;

-- 创建交易记录表
CREATE TABLE IF NOT EXISTS transactions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  portfolio_id INT NOT NULL,
  type ENUM('BUY', 'SELL') NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  shares INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  total DECIMAL(15,2) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
) ENGINE=InnoDB;
