const top50Stocks = [
  {
    Symbol: "NVDA",
    Name: "NVIDIA Corporation",
    Sector: "TECHNOLOGY",
    Industry: "SEMICONDUCTORS",
    Description:
      "NVIDIA Corporation is an American multinational technology company headquartered in Santa Clara, California. It specializes in graphics processing units (GPUs) for gaming, AI, and professional markets, as well as system-on‑a‑chip units for the mobile computing and automotive market.",
    CIK: "0001045810",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "2788 San Tomas Expressway, Santa Clara, CA, US",
    OfficialSite: "https://www.nvidia.com",
    MarketCapitalization: "4370000000000",
    EBITDA: "67000000000",
    PERatio: "49.2",
    PEGRatio: "2.8",
    BookValue: "4.15"
  },
  {
    Symbol: "MSFT",
    Name: "Microsoft Corporation",
    Sector: "TECHNOLOGY",
    Industry: "SOFTWARE—INFRASTRUCTURE",
    Description:
      "Microsoft Corporation is a global technology company headquartered in Redmond, Washington. It develops, licenses, and supports software, services, devices and solutions, most notably Windows, Office and Azure cloud platform.",
    CIK: "0000789019",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "One Microsoft Way, Redmond, WA, US",
    OfficialSite: "https://www.microsoft.com",
    MarketCapitalization: "3810000000000",
    EBITDA: "125000000000",
    PERatio: "35.3",
    PEGRatio: "2.4",
    BookValue: "30.12"
  },
  {
    Symbol: "AAPL",
    Name: "Apple Inc.",
    Sector: "TECHNOLOGY",
    Industry: "CONSUMER ELECTRONICS",
    Description:
      "Apple Inc. designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories worldwide. Known for the iPhone, iPad, Mac, Apple Watch and Apple TV.",
    CIK: "0000320193",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "One Apple Park Way, Cupertino, CA, US",
    OfficialSite: "https://www.apple.com",
    MarketCapitalization: "3120000000000",
    EBITDA: "136000000000",
    PERatio: "31.6",
    PEGRatio: "2.0",
    BookValue: "5.00"
  },
  {
    Symbol: "AMZN",
    Name: "Amazon.com, Inc.",
    Sector: "CONSUMER DISCRETIONARY",
    Industry: "INTERNET RETAIL",
    Description:
      "Amazon.com, Inc. is a global e-commerce and cloud computing company based in Seattle. Offers online retail, digital streaming, AI services, and logistics. Operates Amazon Web Services.",
    CIK: "0001018724",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "410 Terry Ave N, Seattle, WA, US",
    OfficialSite: "https://www.amazon.com",
    MarketCapitalization: "2440000000000",
    EBITDA: "83000000000",
    PERatio: "56.1",
    PEGRatio: "2.6",
    BookValue: "16.7"
  },
  {
    Symbol: "GOOG",
    Name: "Alphabet Inc. Class C",
    Sector: "COMMUNICATION SERVICES",
    Industry: "INTERNET CONTENT & INFORMATION",
    Description:
      "Alphabet Inc. is the parent company of Google and other businesses. Provides search, advertising, cloud computing, operating systems, and smart devices.",
    CIK: "0001652044",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "1600 Amphitheatre Parkway, Mountain View, CA, US",
    OfficialSite: "https://www.abc.xyz",
    MarketCapitalization: "2390000000000",
    EBITDA: "92000000000",
    PERatio: "30.5",
    PEGRatio: "1.9",
    BookValue: "5.40"
  },
  {
    Symbol: "GOOGL",
    Name: "Alphabet Inc. Class A",
    Sector: "COMMUNICATION SERVICES",
    Industry: "INTERNET CONTENT & INFORMATION",
    Description:
      "Alphabet Inc. is the parent company of Google and other businesses. Class A shares provide voting rights.",
    CIK: "0001652044",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "1600 Amphitheatre Parkway, Mountain View, CA, US",
    OfficialSite: "https://www.abc.xyz",
    MarketCapitalization: "2380000000000",
    EBITDA: "92000000000",
    PERatio: "30.3",
    PEGRatio: "1.9",
    BookValue: "5.42"
  },
  {
    Symbol: "META",
    Name: "Meta Platforms, Inc.",
    Sector: "COMMUNICATION SERVICES",
    Industry: "INTERNET CONTENT & INFORMATION",
    Description:
      "Meta Platforms is the parent company of Facebook, Instagram, WhatsApp, and Oculus. It develops social media, VR, and AI applications.",
    CIK: "0001326801",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "1 Hacker Way, Menlo Park, CA, US",
    OfficialSite: "https://about.meta.com",
    MarketCapitalization: "1750000000000",
    EBITDA: "72000000000",
    PERatio: "28.4",
    PEGRatio: "1.7",
    BookValue: "53.18"
  },
  {
    Symbol: "AVGO",
    Name: "Broadcom Inc.",
    Sector: "TECHNOLOGY",
    Industry: "SEMICONDUCTORS",
    Description:
      "Broadcom Inc. is a global technology leader that designs, develops and supplies a broad range of semiconductor and infrastructure software solutions.",
    CIK: "0001730168",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "1320 Ridder Park Dr, San Jose, CA, US",
    OfficialSite: "https://www.broadcom.com",
    MarketCapitalization: "1420000000000",
    EBITDA: "22000000000",
    PERatio: "34.1",
    PEGRatio: "2.2",
    BookValue: "46.7"
  },
  {
    Symbol: "TSM",
    Name: "Taiwan Semiconductor Manufacturing Company Limited",
    Sector: "TECHNOLOGY",
    Industry: "SEMICONDUCTORS",
    Description:
      "TSMC is a Taiwanese multinational semiconductor contract manufacturing and design company. It is the world's largest dedicated independent semiconductor foundry.",
    CIK: "0001046179",
    Exchange: "NYSE",
    Currency: "USD",
    Country: "Taiwan",
    Address: "No. 8, Li-Hsin Rd. 6, Hsinchu Science Park, Hsinchu, Taiwan",
    OfficialSite: "https://www.tsmc.com",
    MarketCapitalization: "1260000000000",
    EBITDA: "58000000000",
    PERatio: "26.7",
    PEGRatio: "1.4",
    BookValue: "10.28"
  },
  {
    Symbol: "TSLA",
    Name: "Tesla, Inc.",
    Sector: "CONSUMER DISCRETIONARY",
    Industry: "AUTO MANUFACTURERS",
    Description:
      "Tesla designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.",
    CIK: "0001318605",
    Exchange: "NASDAQ",
    Currency: "USD",
    Country: "USA",
    Address: "3500 Deer Creek Road, Palo Alto, CA, US",
    OfficialSite: "https://www.tesla.com",
    MarketCapitalization: "1030000000000",
    EBITDA: "18000000000",
    PERatio: "70.2",
    PEGRatio: "2.9",
    BookValue: "16.08"
  },
  {
    Symbol: "BRK.A",
    Name: "Berkshire Hathaway Inc. Class A",
    Sector: "FINANCIALS",
    Industry: "INSURANCE—DIVERSIFIED",
    Description:
      "Berkshire Hathaway is a multinational conglomerate holding company led by Warren Buffett. It owns a range of subsidiaries across insurance, utilities, railroads, and more.",
    CIK: "0001067983",
    Exchange: "NYSE",
    Currency: "USD",
    Country: "USA",
    Address: "3555 Farnam Street, Omaha, NE, US",
    OfficialSite: "https://www.berkshirehathaway.com",
    MarketCapitalization: "1030000000000",
    EBITDA: "75000000000",
    PERatio: "21.3",
    PEGRatio: "1.8",
    BookValue: "375899"
  },
  {
    Symbol: "BRK.B",
    Name: "Berkshire Hathaway Inc. Class B",
    Sector: "FINANCIALS",
    Industry: "INSURANCE—DIVERSIFIED",
    Description:
      "Berkshire Hathaway is a multinational conglomerate holding company led by Warren Buffett. Class B shares offer lower price and no voting rights.",
    CIK: "0001067983",
    Exchange: "NYSE",
    Currency: "USD",
    Country: "USA",
    Address: "3555 Farnam Street, Omaha, NE, US",
    OfficialSite: "https://www.berkshirehathaway.com",
    MarketCapitalization: "1030000000000",
    EBITDA: "75000000000",
    PERatio: "21.5",
    PEGRatio: "1.9",
    BookValue: "327"
  }
];
